from typing import List

from pygame.event import Event as PYGEvent
import framebuf

class Event():
    def __init__(self, pyg_event: PYGEvent) -> None: ...

class SSD1306_Emu(framebuf.FrameBuffer):
    width: int
    height: int
    def __init__(self, width: int, height: int, *args, main_process = ..., ignore_pygame_event = ..., **kws) -> None: ...
    def _get_pygame_event(self) -> List[Event]: ...
    def _pygame_loop(self, wait=...) -> None: ...
    def _pygame_stop(self) -> None: ...
    def poweroff(self) -> None: ...
    def poweron(self) -> None: ...
    def contrast(self, contrast: int) -> None: ...
    def invert(self, invert: bool) -> None: ...
    def show(self) -> None: ...
    def refresh(self, x: int, y: int, w: int, h: int) -> None: ...
